# Use this compose file for running the entire application from within containers.
# application 'myapp' will be pulled from AWS ECR and MongoDB and Mongo Express will be pulled from DockerHub.
version: '3'
services:
  myapp:
    image: 172763042044.dkr.ecr.us-east-1.amazonaws.com/myapp:1.0
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongodb-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always # mongo express has to wait till mongodb container is up and running
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
volumes:
  mongodb-data:
    driver: local
